# Cloud Build configuration for building and deploying the Luxe API to Cloud Run
# Assumes Artifact Registry repo already exists (set _REGION and _REPO vars)
# Substitutions expected:
# _REGION=us-central1
# _SERVICE_NAME=luxe-api
# _REPO=luxe-repo
# _PROJECT_ID=your-gcp-project
# _IMAGE_TAG=latest (or CI commit SHA)
# Optionally: _RUN_REGION=us-central1

steps:
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Install deps'
    args: ['ci']

  - name: 'gcr.io/cloud-builders/npm'
    id: 'Run tests'
    args: ['run', 'test']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build image'
    args:
      - 'build'
      - '-t'
      - '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO/$_SERVICE_NAME:$_IMAGE_TAG'
      - '-t'
      - '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO/$_SERVICE_NAME:$COMMIT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push image'
    args:
      - 'push'
      - '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO/$_SERVICE_NAME:$_IMAGE_TAG'
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push image (SHA)'
    args:
      - 'push'
      - '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO/$_SERVICE_NAME:$COMMIT_SHA'

  # Optional: run migrations inside a temporary container (requires DATABASE_URL secret)
  - name: '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO/$_SERVICE_NAME:$_IMAGE_TAG'
    id: 'Run migrations'
    entrypoint: 'sh'
    secretEnv: [ 'DATABASE_URL' ]
    args:
      - '-c'
      - 'node dist/migrate.js || echo "Migration script not found (ensure build includes migrations)"'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Cloud Run'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy $_SERVICE_NAME \
          --image $_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO/$_SERVICE_NAME:$COMMIT_SHA \
          --region ${_RUN_REGION:-$_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars=NODE_ENV=production,PORT=8080

images:
  - '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO/$_SERVICE_NAME:$COMMIT_SHA'

# Secrets manager integration (add DATABASE_URL secret with Cloud Build access)
availableSecrets:
  secretManager:
    - versionName: projects/$_PROJECT_ID/secrets/DATABASE_URL/versions/latest
      env: DATABASE_URL
