export type Product = {
  id?: number;
  slug: string;
  name: string;
  category: "Vêtements" | "Parfums et Cosmétiques" | "Chaussures" | "Montres" | "Accessoires";
  priceXaf: number;
  promoPriceXaf?: number;
  materials: string[];
  colors: string[];
  sizes: string[];
  fit: string;
  limitedAvailability?: boolean;
  seasonalEdit?: string;
  description: string;
  details: string[];
  care: string[];
  imageUrl?: string;
  images?: string[];
  editorNote?: string;
  stock?: number;
};

export const products: Product[] = [
  {
    slug: "seasonal-wrap-coat",
    name: "Manteau portefeuille saisonnier",
    category: "Vêtements",
    priceXaf: 125000,
    materials: ["Mélange laine"],
    colors: ["Charbon"],
    sizes: ["XS", "S", "M", "L"],
    fit: "Décontractée",
    limitedAvailability: true,
    seasonalEdit: "Édition exclusive",
    description: "Une silhouette calme au tombé volontaire.",
    details: [
      "Fermeture portefeuille avec lien intérieur",
      "Épaules souplement structurées",
      "Proportion allongée",
    ],
    care: ["Nettoyage à sec", "Vapeur légère", "Ranger plié ou sur cintre large"],
  },
  {
    slug: "atelier-satin-shirt",
    name: "Chemise satin Atelier",
    category: "Vêtements",
    priceXaf: 68000,
    materials: ["Satin"],
    colors: ["Ivoire"],
    sizes: ["XS", "S", "M", "L"],
    fit: "Aisée",
    seasonalEdit: "La sélection curatée",
    description: "Un éclat doux, une structure silencieuse.",
    details: ["Patte de boutonnage cachée", "Poignet aux surpiqûres fines", "Ligne fluide"],
    care: ["Lavage à la main à froid", "Séchage à plat", "Repassage doux sur l’envers"],
  },
  {
    slug: "quiet-knit-crew",
    name: "Pull maille essentielle",
    category: "Vêtements",
    priceXaf: 54000,
    materials: ["Coton"],
    colors: ["Sable", "Charbon"],
    sizes: ["XS", "S", "M", "L", "XL"],
    fit: "Classique",
    seasonalEdit: "Les essentiels",
    description: "Une maille fondatrice au poids juste.",
    details: ["Col et poignets côtelés", "Finition bas propre", "Main douce"],
    care: ["Lavage machine à froid", "Séchage à plat", "Éviter le sèche-linge"],
  },
  {
    slug: "stone-linen-trouser",
    name: "Pantalon lin taupe pierre",
    category: "Vêtements",
    priceXaf: 72000,
    materials: ["Lin"],
    colors: ["Taupe pierre"],
    sizes: ["XS", "S", "M", "L"],
    fit: "Droite",
    seasonalEdit: "La sélection curatée",
    description: "Un lin respirant, taillé avec retenue.",
    details: ["Taille haute", "Pli marqué", "Ajusteurs sur les côtés"],
    care: ["Lavage machine à froid", "Vapeur pour remettre en forme", "Séchage sur fil"],
  },
  {
    slug: "porcelain-tee",
    name: "T-shirt porcelaine",
    category: "Vêtements",
    priceXaf: 24000,
    materials: ["Coton"],
    colors: ["Porcelaine"],
    sizes: ["XS", "S", "M", "L", "XL"],
    fit: "Classique",
    seasonalEdit: "Les essentiels",
    description: "Une base nette à la coupe pensée.",
    details: ["Encolure douce", "Manche équilibrée", "Matière opaque"],
    care: ["Lavage machine à froid", "Sèche-linge doux", "Ne pas blanchir"],
  },
  {
    slug: "cypress-scarf",
    name: "Écharpe cyprès",
    category: "Accessoires",
    priceXaf: 32000,
    materials: ["Laine"],
    colors: ["Cyprès"],
    sizes: ["Taille unique"],
    fit: "Tombé",
    limitedAvailability: true,
    seasonalEdit: "Édition exclusive",
    description: "Un accent discret, toujours serein.",
    details: ["Bords adoucis", "Chaleur légère", "Pli compact"],
    care: ["Nettoyage à sec", "Aérer entre les ports"],
  },
  {
    slug: "atelier-slip-dress",
    name: "Robe nuisette Atelier",
    category: "Vêtements",
    priceXaf: 98000,
    materials: ["Satin"],
    colors: ["Charbon"],
    sizes: ["XS", "S", "M", "L"],
    fit: "Fluide",
    seasonalEdit: "L’Atelier",
    description: "Des lignes minimales, un mouvement tactile.",
    details: ["Coupe en biais", "Bretelles réglables", "Éclat subtil"],
    care: ["Lavage à la main à froid", "Vapeur légère"],
  },
  {
    slug: "sand-canvas-tote",
    name: "Cabas toile sable",
    category: "Accessoires",
    priceXaf: 41000,
    materials: ["Toile"],
    colors: ["Sable"],
    sizes: ["Taille unique"],
    fit: "Porté",
    seasonalEdit: "Les essentiels",
    description: "Une utilité quotidienne, élevée par la proportion.",
    details: ["Anses larges", "Poche intérieure", "Base structurée"],
    care: ["Nettoyer localement", "Séchage à l’air"],
  },
  {
    slug: "bone-silk-scarf",
    name: "Foulard soie ivoire",
    category: "Accessoires",
    priceXaf: 45000,
    materials: ["Soie"],
    colors: ["Ivoire"],
    sizes: ["Taille unique"],
    fit: "Tombé",
    seasonalEdit: "La sélection curatée",
    description: "Une lumière douce, un bord raffiné.",
    details: ["Ourlet roulotté", "Soie légère", "Pli polyvalent"],
    care: ["Nettoyage à sec", "Ranger à plat"],
  },
  {
    slug: "atelier-overshirt",
    name: "Surchemise Atelier",
    category: "Vêtements",
    priceXaf: 88000,
    materials: ["Coton"],
    colors: ["Ardoise"],
    sizes: ["S", "M", "L", "XL"],
    fit: "Décontractée",
    seasonalEdit: "L’Atelier",
    description: "Une couche qui se lit intentionnelle, jamais bruyante.",
    details: ["Ligne de poche nette", "Col souple", "Texture mate"],
    care: ["Lavage machine à froid", "Séchage sur fil", "Vapeur pour finir"],
  },
  {
    slug: "stone-knit-cardigan",
    name: "Cardigan maille taupe pierre",
    category: "Vêtements",
    priceXaf: 76000,
    materials: ["Mélange laine"],
    colors: ["Taupe pierre"],
    sizes: ["XS", "S", "M", "L"],
    fit: "Décontractée",
    seasonalEdit: "Édition exclusive",
    description: "De la chaleur avec un calme éditorial.",
    details: ["Boutonnage devant", "Finition côtelée", "Tombé doux"],
    care: ["Nettoyage à sec", "Séchage à plat"],
  },
  {
    slug: "charcoal-tailored-skirt",
    name: "Jupe tailleur charbon",
    category: "Vêtements",
    priceXaf: 69000,
    materials: ["Mélange laine"],
    colors: ["Charbon"],
    sizes: ["XS", "S", "M", "L"],
    fit: "Droite",
    seasonalEdit: "La sélection curatée",
    description: "Une ligne nette, une finition précise.",
    details: ["Fente dos", "Zip invisible", "Doublée"],
    care: ["Nettoyage à sec", "Vapeur pour remettre en forme"],
  },
  {
    slug: "atelier-sandals",
    name: "Sandales Atelier",
    category: "Chaussures",
    priceXaf: 65000,
    materials: ["Cuir"],
    colors: ["Sable"],
    sizes: ["38", "39", "40", "41", "42"],
    fit: "Ajustée",
    seasonalEdit: "La sélection curatée",
    description: "Une ligne ouverte, pensée pour la chaleur et la retenue.",
    details: ["Bride fine", "Semelle confortable", "Finition mate"],
    care: ["Nettoyer avec un chiffon doux", "Éviter l’eau prolongée", "Ranger avec embauchoirs"],
  },
  {
    slug: "quiet-loafers",
    name: "Mocassins cuir lisse",
    category: "Chaussures",
    priceXaf: 82000,
    materials: ["Cuir"],
    colors: ["Charbon"],
    sizes: ["39", "40", "41", "42", "43", "44"],
    fit: "Classique",
    seasonalEdit: "Les essentiels",
    description: "Un essentiel net : confort et structure, sans démonstration.",
    details: ["Couture discrète", "Semelle fine", "Forme équilibrée"],
    care: ["Appliquer une crème neutre", "Brosser légèrement", "Laisser respirer"],
  },
  {
    slug: "minimal-ankle-boots",
    name: "Bottines minimalistes",
    category: "Chaussures",
    priceXaf: 99000,
    materials: ["Cuir"],
    colors: ["Ardoise"],
    sizes: ["39", "40", "41", "42", "43"],
    fit: "Ajustée",
    limitedAvailability: true,
    seasonalEdit: "Édition exclusive",
    description: "Une présence sobre, une silhouette affûtée.",
    details: ["Tige courte", "Zip invisible", "Talon stable"],
    care: ["Imperméabiliser avant port", "Sécher à l’air", "Ranger avec embauchoirs"],
  },
  {
    slug: "santal-clair-edp",
    name: "Eau de parfum — Santal clair",
    category: "Parfums et Cosmétiques",
    priceXaf: 58000,
    materials: ["Essences naturelles"],
    colors: ["Ambre"],
    sizes: ["50 ml", "100 ml"],
    fit: "Standard",
    seasonalEdit: "La sélection curatée",
    description: "Un bois doux et lumineux. Une trace propre, très proche de la peau.",
    details: ["Notes: santal, musc, figue", "Sillage discret", "Vaporisation fine"],
    care: ["Conserver à l’abri de la chaleur", "Éviter la lumière directe"],
  },
  {
    slug: "cypres-body-oil",
    name: "Huile de corps — Cyprès",
    category: "Parfums et Cosmétiques",
    priceXaf: 34000,
    materials: ["Huiles végétales"],
    colors: ["Cyprès"],
    sizes: ["100 ml"],
    fit: "Standard",
    seasonalEdit: "Les essentiels",
    description: "Une texture légère qui nourrit sans alourdir, au parfum vert et calme.",
    details: ["Fini satiné", "Absorption rapide", "Parfum subtil"],
    care: ["Appliquer sur peau légèrement humide", "Refermer après usage"],
  },
  {
    slug: "ivory-hand-balm",
    name: "Baume mains — Ivoire",
    category: "Parfums et Cosmétiques",
    priceXaf: 19000,
    materials: ["Beurre végétal"],
    colors: ["Ivoire"],
    sizes: ["50 ml"],
    fit: "Standard",
    limitedAvailability: true,
    seasonalEdit: "Édition exclusive",
    description: "Un soin dense, fini sec. Pour les gestes répétés, sans parfum dominant.",
    details: ["Texture riche", "Fini non gras", "Parfum minimal"],
    care: ["Conserver fermé", "Éviter les fortes chaleurs"],
  },
  {
    slug: "brushed-steel-watch",
    name: "Montre — Acier brossé",
    category: "Montres",
    priceXaf: 145000,
    materials: ["Acier inoxydable"],
    colors: ["Acier"],
    sizes: ["Taille unique"],
    fit: "Ajustable",
    seasonalEdit: "Les essentiels",
    description: "Lecture nette, finition mate. Une présence qui reste tranquille.",
    details: ["Bracelet ajustable", "Verre minéral", "Cadran clair"],
    care: ["Essuyer avec un chiffon doux", "Éviter les chocs", "Ranger à l’abri"],
  },
  {
    slug: "pale-gold-watch",
    name: "Montre — Or pâle",
    category: "Montres",
    priceXaf: 175000,
    materials: ["Acier inoxydable"],
    colors: ["Or pâle"],
    sizes: ["Taille unique"],
    fit: "Ajustable",
    seasonalEdit: "La sélection curatée",
    description: "Une chaleur douce, un éclat maîtrisé.",
    details: ["Finition satinée", "Bracelet réglable", "Index minimal"],
    care: ["Éviter les produits chimiques", "Nettoyer avec un chiffon sec"],
  },
  {
    slug: "charcoal-dial-watch",
    name: "Montre — Cadran charbon",
    category: "Montres",
    priceXaf: 165000,
    materials: ["Acier inoxydable"],
    colors: ["Charbon"],
    sizes: ["Taille unique"],
    fit: "Ajustable",
    limitedAvailability: true,
    seasonalEdit: "Édition exclusive",
    description: "Un contraste calme. Une précision lisible.",
    details: ["Cadran sombre", "Aiguilles fines", "Finition mate"],
    care: ["Essuyer après port", "Éviter l’eau prolongée", "Ranger à l’abri"],
  },
];
